spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/blog?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: blog
    password: sql123456