server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/security?serverTimezone=Asia/Seoul
    username: cos
    password: sql123456

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 317834341435-hek2dtg1j7ebfmp9puqmllck8vcsclab.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
            
          facebook:
            client-id: 1120308305348957
            client-secret: ef029776a246cf996bb1a3ff1201f1b0
            scope:
            - email
            - public_profile
            
          naver:
            client-id: YWRWjrkRH0P0qlAuDANG
            client-secret: zqI7Sq5WJb
            scope:
            - name
            - profile
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            
            
        provider: 
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json의 response 키값으로 리턴해줌.
            